first_number = input('enter the first number\n')
second_number = input('enter the second number\n')
sum = str(int(first_number) + int(second_number))
multiply = str(int(first_number) * int(second_number))
sub = str(int(first_number) - int(second_number))
div = str(int(first_number) / int(second_number))
print('The sum of ' + first_number  + ' and '   +  second_number  + ' is\n' + sum)
print('The multiplication  of  ' + first_number  + ' and '   +  second_number  + ' is\n' + multiply)
print('The substraction  of  ' + first_number  + ' and '   +  second_number  + ' is\n' + sub)
print('The division  of  ' + first_number  + ' and '   +  second_number  + ' is\n' + div)
